# Build stage
FROM maven:3.8.1-openjdk-17-slim AS build
WORKDIR /app

COPY pom.xml .
COPY shopme-common/pom.xml ./shopme-common/
COPY shopme-webparent/pom.xml ./shopme-webparent/
COPY shopme-webparent/shopme-client/pom.xml ./shopme-webparent/shopme-client/

RUN mvn -B -N dependency:go-offline

COPY . .
RUN mvn -B package -DskipTests

# Run stage
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/shopme-webparent/shopme-client/target/*.jar ./app.jar
EXPOSE 80
ENTRYPOINT ["java", "-jar", "app.jar"]